version: 2
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 5
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
